"""Information-Extraction-specific evaluation metrics.

LLaMA-Factory's built-in ``eval`` command is designed for perplexity and
multiple-choice benchmarks; it does not know how to grade KV / entity /
relation extraction. This module provides the generation-based metrics
you actually want for an IE SFT run:

* KV extraction -> per-field exact-match F1 over all (record, field) pairs.
* Entity extraction -> set-level F1 over (type, text) tuples.
* Relation extraction -> set-level F1 over (head, relation, tail) triples,
                          with an optional ``+types`` stricter variant.

All functions are pure Python and accept lists of predictions and golds in
the canonical ``Answer`` shape (see ``src.common.schema``). Predictions
that fail to parse as valid Answer JSON are counted as empty predictions,
which lowers recall but never crashes the run.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any, Iterable

from src.common.logging_utils import get_logger

logger = get_logger(__name__)


# ---------------------------------------------------------------------------
# Prediction parsing
# ---------------------------------------------------------------------------

EXPECTED_TOP_LEVEL_KEYS = ("kv", "entity", "relation")


def parse_prediction(raw: str) -> dict[str, Any]:
    """Parse a raw model output string into an Answer-shaped dict.

    The model is instructed to emit strict JSON, but real outputs often
    include prompt echo, code fences, or garbage after an otherwise valid
    JSON answer. We recover by scanning for the first parseable balanced
    JSON object, prioritizing text after the final ``Output:`` marker.

    Args:
        raw: The raw text generated by the model.

    Returns:
        A dict with at least ``kv`` / ``entity`` / ``relation`` keys
        (missing keys are backfilled with empty containers). Malformed
        predictions resolve to empty containers rather than raising.
    """
    parsed, _ = _parse_prediction_with_status(raw)
    return parsed


def _parse_prediction_with_status(raw: str) -> tuple[dict[str, Any], bool]:
    """Parse a prediction and report whether JSON recovery succeeded.

    Collects ALL parseable JSON answer dicts from all candidate regions
    and picks the richest one (most entity + relation content).
    """
    empty = _empty_answer()
    if not raw:
        return empty, False

    text = raw.strip()
    candidates = _candidate_regions(text)

    all_parsed: list[dict[str, Any]] = []

    for region in candidates:
        parsed = _loads_answer_dict(region)
        if parsed is not None:
            all_parsed.append(parsed)

        for block in _iter_balanced_json_objects(region):
            parsed = _loads_answer_dict(block)
            if parsed is not None:
                all_parsed.append(parsed)

    if not all_parsed:
        return empty, False

    # Pick the richest result: most entity + relation items
    best = max(all_parsed, key=_answer_richness)
    return best, True


def _answer_richness(answer: dict[str, Any]) -> int:
    """Score an answer dict by how much content it has."""
    return (
        len(answer.get("entity", []))
        + len(answer.get("relation", [])) * 2  # relations are higher value
        + len(answer.get("kv", {}))
    )


def _empty_answer() -> dict[str, Any]:
    return {"kv": {}, "entity": [], "relation": []}


_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL)
_UNCLOSED_THINK_RE = re.compile(r"<think>.*", re.DOTALL)

# Placeholder values from the prompt template that indicate the model
# echoed the format example rather than producing real extractions.
# ONLY includes literal template tokens — NOT legitimate entity types
# that happen to be uppercase (e.g. "HUMAN", "PRODUCT", "REGION").
_KV_PLACEHOLDER_KEYS = frozenset({
    "field_name", "value_or_null",
})
_ENTITY_TEXT_PLACEHOLDERS = frozenset({
    "entity_text", "head_text", "tail_text",
})
_TYPE_PLACEHOLDERS = frozenset({
    "ENTITY_TYPE", "HEAD_TYPE", "TAIL_TYPE", "RELATION_TYPE",
})
_OFFSET_PLACEHOLDERS = frozenset({
    "offset_start", "offset_end",
})


def _strip_think_tags(text: str) -> str:
    """Remove ``<think>…</think>`` blocks produced by Qwen3 thinking mode."""
    cleaned = _THINK_RE.sub("", text).strip()
    # Handle unclosed <think> — discard from <think> onward.
    cleaned = _UNCLOSED_THINK_RE.sub("", cleaned).strip()
    return cleaned


def _candidate_regions(text: str) -> list[str]:
    """Build candidate regions, prioritizing the generated answer area.

    Handles: prompt echo, <think> tags, code fences (closed and unclosed),
    multiple ``Output:`` markers, and combinations thereof.
    """
    regions: list[str] = []

    def add(candidate: str) -> None:
        candidate = candidate.strip()
        if candidate and candidate not in regions:
            regions.append(candidate)

    # 1. Strip <think> tags (Qwen3 thinking mode)
    text_clean = _strip_think_tags(text)

    # 2. Find ALL "Output:" markers — the LAST one is most likely the real answer.
    #    Model often echoes the full prompt which itself contains "Output:" at the end.
    marker = "output:"
    for source in (text_clean, text) if text_clean != text else (text_clean,):
        lowered = source.lower()
        positions: list[int] = []
        start = 0
        while True:
            idx = lowered.find(marker, start)
            if idx == -1:
                break
            positions.append(idx + len(marker))
            start = idx + len(marker)

        # Iterate in reverse — last Output: is most likely the answer
        for pos in reversed(positions):
            after = source[pos:]
            add(_strip_code_fence(after))

    # 3. Fallback: just try the whole text (after think removal + fence strip)
    add(_strip_code_fence(text_clean))
    add(_strip_code_fence(text))

    return regions


def _strip_code_fence(text: str) -> str:
    """Unwrap markdown code fences, handling both closed and unclosed fences."""
    stripped = text.strip()
    if not stripped.startswith("```"):
        # Also check for fence appearing after some whitespace/newline
        idx = stripped.find("```")
        if idx != -1 and idx < 20:  # fence near the start
            stripped = stripped[idx:]
        else:
            return stripped

    lines = stripped.splitlines()
    # Skip the opening ``` line (may have language tag like ```json)
    body_start = 1
    # Find closing ```
    body_end = len(lines)
    for i in range(len(lines) - 1, 0, -1):
        if lines[i].strip().startswith("```"):
            body_end = i
            break

    body = lines[body_start:body_end]
    return "\n".join(body).strip()


def _iter_balanced_json_objects(text: str) -> Iterable[str]:
    """Yield balanced top-level JSON objects in source order."""
    start: int | None = None
    depth = 0
    in_string = False
    escaping = False

    for idx, ch in enumerate(text):
        if start is None:
            if ch == "{":
                start = idx
                depth = 1
                in_string = False
                escaping = False
            continue

        if in_string:
            if escaping:
                escaping = False
            elif ch == "\\":
                escaping = True
            elif ch == '"':
                in_string = False
            continue

        if ch == '"':
            in_string = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                yield text[start : idx + 1]
                start = None

    # If there's an unclosed JSON object, try to repair it
    if start is not None:
        truncated = text[start:]
        repaired = _try_repair_truncated_json(truncated)
        if repaired is not None:
            yield repaired


def _try_repair_truncated_json(text: str) -> str | None:
    """Attempt to repair truncated JSON by closing open brackets/braces.

    Handles the common case where max_new_tokens cuts off mid-JSON.
    Uses multiple strategies:
    1. Strip back to the last complete object/array element.
    2. Close all remaining open containers.
    3. If that fails, try progressively stripping trailing incomplete items.
    """
    if not text or "{" not in text:
        return None

    # Strategy: try multiple truncation points, from least to most aggressive
    candidates: list[str] = []

    s = text.rstrip()
    # Remove trailing incomplete string (unclosed quote)
    s = _strip_unclosed_string(s)
    # Remove trailing partial tokens
    s = re.sub(r'[,:\s]+$', '', s)
    candidates.append(s)

    # Also try stripping back to the last complete } or ]
    for closer in ('}', ']', '"}', '"]'):
        idx = s.rfind(closer)
        if idx != -1:
            candidates.append(s[:idx + len(closer)])

    # Also try stripping back to the last complete }, then close containers
    for cand in candidates:
        cand = re.sub(r'[,:\s]+$', '', cand)
        repaired = _close_containers(cand)
        if repaired is not None:
            return repaired

    return None


def _strip_unclosed_string(s: str) -> str:
    """Remove a trailing unclosed string from JSON text."""
    in_string = False
    escaping = False
    last_outside = 0
    for i, ch in enumerate(s):
        if in_string:
            if escaping:
                escaping = False
            elif ch == "\\":
                escaping = True
            elif ch == '"':
                in_string = False
                last_outside = i + 1
        else:
            if ch == '"':
                in_string = True
            else:
                last_outside = i + 1
    return s[:last_outside] if in_string else s


def _close_containers(s: str) -> str | None:
    """Close unbalanced { and [ then try to parse."""
    depth_brace = 0
    depth_bracket = 0
    in_str = False
    esc = False
    for ch in s:
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == '{':
            depth_brace += 1
        elif ch == '}':
            depth_brace -= 1
        elif ch == '[':
            depth_bracket += 1
        elif ch == ']':
            depth_bracket -= 1

    if depth_brace <= 0 and depth_bracket <= 0:
        # Already balanced — try parsing directly
        try:
            json.loads(s)
            return s
        except json.JSONDecodeError:
            return None

    repaired = s + ']' * max(0, depth_bracket) + '}' * max(0, depth_brace)
    try:
        json.loads(repaired)
        return repaired
    except json.JSONDecodeError:
        return None


def _sanitize_template_noise(text: str) -> str:
    """Remove template placeholder noise that base models echo verbatim.

    Base (non-fine-tuned) models often echo the prompt format example,
    producing invalid JSON containing literal ``...``, ``offset_start``,
    ``"field_name": "field_value"``, etc.  This function strips these
    patterns so the remaining JSON can be parsed.
    """
    # 1. Remove lines that are just "..." or "    ..." (ellipsis placeholders)
    text = re.sub(r',?\s*\.\.\.\s*\n?', '\n', text)

    # 2. Remove trailing "..." before closing ] or }
    text = re.sub(r',?\s*\.\.\.\s*([}\]])', r'\1', text)

    # 3. Replace literal template tokens used as values:
    #    "start": offset_start  ->  "start": null
    #    "end": offset_end      ->  "end": null
    text = re.sub(r':\s*offset_start\b', ': null', text)
    text = re.sub(r':\s*offset_end\b', ': null', text)

    # 4. Remove KV placeholder entries: "field_name": "field_value"
    #    and "field_name": "value_or_null"
    text = re.sub(
        r'"field_name"\s*:\s*"[^"]*"\s*,?\s*', '', text
    )
    text = re.sub(
        r'"field_value"\s*:\s*"[^"]*"\s*,?\s*', '', text
    )

    # 5. Clean up trailing commas before } or ]
    text = re.sub(r',\s*([}\]])', r'\1', text)

    return text


def _loads_answer_dict(candidate: str) -> dict[str, Any] | None:
    """Parse one candidate string into the normalized answer structure.

    Tries direct parse first, then truncated JSON repair, and only
    applies template noise sanitization as a LAST RESORT to avoid
    destructively modifying already-parseable outputs from fine-tuned models.
    """
    # Try direct parse
    parsed = _try_parse_json(candidate)
    if parsed is not None:
        return parsed

    # Try repair if it looks like truncated JSON
    repaired = _try_repair_truncated_json(candidate)
    if repaired is not None:
        parsed = _try_parse_json(repaired)
        if parsed is not None:
            return parsed

    # LAST RESORT: sanitize template noise (base model echo patterns)
    # Only apply if direct parse and repair both failed — this avoids
    # destructively modifying fine-tuned model outputs that use
    # "field_name" as a literal key in their JSON.
    sanitized = _sanitize_template_noise(candidate)
    if sanitized != candidate:
        parsed = _try_parse_json(sanitized)
        if parsed is not None:
            return parsed
        # Also try repair on sanitized version
        repaired = _try_repair_truncated_json(sanitized)
        if repaired is not None:
            parsed = _try_parse_json(repaired)
            if parsed is not None:
                return parsed

    return None


def _try_parse_json(candidate: str) -> dict[str, Any] | None:
    """Attempt to parse candidate as JSON and validate it's an answer dict.

    Also tries to fix common JSON syntax errors (missing commas).
    """
    for attempt in (candidate, _fix_json_syntax(candidate)):
        if attempt is None:
            continue
        try:
            parsed = json.loads(attempt)
        except json.JSONDecodeError:
            continue

        if not isinstance(parsed, dict):
            continue
        if not any(key in parsed for key in EXPECTED_TOP_LEVEL_KEYS):
            continue
        return _normalize_answer_dict(parsed)
    return None


def _fix_json_syntax(text: str) -> str | None:
    """Try to fix common JSON syntax errors like missing commas."""
    # Fix missing comma between } { or } [ or ] { in arrays
    fixed = re.sub(r'\}\s*\{', '},{', text)
    fixed = re.sub(r'\}\s*\[', '},[', fixed)
    fixed = re.sub(r'\]\s*\{', '],{', fixed)
    if fixed != text:
        return fixed
    return None


def _normalize_answer_dict(parsed: dict[str, Any]) -> dict[str, Any]:
    """Backfill missing keys, coerce types, filter placeholders, and de-dup."""
    result: dict[str, Any] = {
        "kv": parsed.get("kv", {}) or {},
        "entity": parsed.get("entity", []) or [],
        "relation": parsed.get("relation", []) or [],
    }
    if not isinstance(result["kv"], dict):
        result["kv"] = {}
    if not isinstance(result["entity"], list):
        result["entity"] = []
    if not isinstance(result["relation"], list):
        result["relation"] = []

    # --- Filter placeholder KV keys (template echo) ---
    result["kv"] = {
        k: v for k, v in result["kv"].items()
        if k not in _KV_PLACEHOLDER_KEYS
        and (isinstance(v, (list, dict)) or str(v) not in _KV_PLACEHOLDER_KEYS)
    }

    # --- Filter placeholder entities (only LITERAL template tokens) ---
    # Keep entities with real text even if type is uppercase/non-standard.
    # Only drop entities whose TEXT is a placeholder (e.g. "entity_text").
    result["entity"] = [
        e for e in result["entity"]
        if isinstance(e, dict)
        and e.get("text") not in _ENTITY_TEXT_PLACEHOLDERS
        and e.get("text")  # must have non-empty text
    ]

    # --- Filter placeholder relations ---
    result["relation"] = [
        r for r in result["relation"]
        if isinstance(r, dict)
        and r.get("head") not in _ENTITY_TEXT_PLACEHOLDERS
        and r.get("tail") not in _ENTITY_TEXT_PLACEHOLDERS
        and r.get("head")  # must have non-empty head
        and r.get("tail")  # must have non-empty tail
    ]

    # --- De-duplicate entities (same text seen multiple times) ---
    seen_entities: set[tuple[str, str]] = set()
    deduped_entities: list[dict] = []
    for e in result["entity"]:
        key = (str(e.get("text", "")), str(e.get("type", "")))
        if key not in seen_entities:
            seen_entities.add(key)
            deduped_entities.append(e)
    result["entity"] = deduped_entities

    # --- De-duplicate relations ---
    seen_rels: set[tuple] = set()
    deduped_rels: list[dict] = []
    for r in result["relation"]:
        key = (
            str(r.get("head", "")),
            str(r.get("relation", "")),
            str(r.get("tail", "")),
        )
        if key not in seen_rels:
            seen_rels.add(key)
            deduped_rels.append(r)
    result["relation"] = deduped_rels

    return result


# ---------------------------------------------------------------------------
# Metric dataclasses
# ---------------------------------------------------------------------------


@dataclass
class PRF1:
    """Precision / recall / F1 bundle with TP/FP/FN counts."""

    precision: float = 0.0
    recall: float = 0.0
    f1: float = 0.0
    tp: int = 0
    fp: int = 0
    fn: int = 0
    support: int = 0  # total golds

    def to_dict(self) -> dict[str, float | int]:
        return {
            "precision": round(self.precision, 4),
            "recall": round(self.recall, 4),
            "f1": round(self.f1, 4),
            "tp": self.tp,
            "fp": self.fp,
            "fn": self.fn,
            "support": self.support,
        }


@dataclass
class IEMetrics:
    """Aggregate IE metrics across all active tasks."""

    kv: PRF1 | None = None
    entity: PRF1 | None = None
    relation: PRF1 | None = None
    relation_typed: PRF1 | None = None  # stricter: also requires matching types
    n_records: int = 0
    n_parse_failures: int = 0
    per_record: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self, include_per_record: bool = False) -> dict[str, Any]:
        d: dict[str, Any] = {
            "n_records": self.n_records,
            "n_parse_failures": self.n_parse_failures,
        }
        if self.kv is not None:
            d["kv"] = self.kv.to_dict()
        if self.entity is not None:
            d["entity"] = self.entity.to_dict()
        if self.relation is not None:
            d["relation"] = self.relation.to_dict()
        if self.relation_typed is not None:
            d["relation_typed"] = self.relation_typed.to_dict()
        if include_per_record:
            d["per_record"] = self.per_record
        return d


# ---------------------------------------------------------------------------
# Core counting helpers
# ---------------------------------------------------------------------------


def _prf1_from_counts(tp: int, fp: int, fn: int, support: int) -> PRF1:
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )
    return PRF1(
        precision=precision,
        recall=recall,
        f1=f1,
        tp=tp,
        fp=fp,
        fn=fn,
        support=support,
    )


def _normalize(text: Any) -> str:
    """Lowercase + collapse whitespace for lenient string matching."""
    if text is None:
        return ""
    return " ".join(str(text).lower().split())


# ---------------------------------------------------------------------------
# Per-task scoring
# ---------------------------------------------------------------------------


def score_kv(
    pred_kvs: Iterable[dict[str, Any]],
    gold_kvs: Iterable[dict[str, Any]],
) -> PRF1:
    """Score KV extraction at the (record, field) level.

    A prediction counts as TP iff the gold also has that field AND the
    normalized string value matches. Missing-in-pred = FN; hallucinated
    field (not in gold) = FP.

    Args:
        pred_kvs: sequence of ``{field: value}`` dicts from predictions.
        gold_kvs: sequence of ``{field: value}`` dicts from gold answers.

    Returns:
        PRF1 summary. ``support`` = total gold (record, field) pairs
        with non-empty values.
    """
    tp = fp = fn = support = 0
    for pred, gold in zip(pred_kvs, gold_kvs):
        pred = pred or {}
        gold = gold or {}
        gold_fields = {k: _normalize(v) for k, v in gold.items() if v not in (None, "")}
        pred_fields = {k: _normalize(v) for k, v in pred.items() if v not in (None, "")}

        support += len(gold_fields)

        for field_name, gold_val in gold_fields.items():
            pred_val = pred_fields.get(field_name)
            if pred_val is None:
                fn += 1
            elif pred_val == gold_val:
                tp += 1
            else:
                fn += 1
                fp += 1  # wrong value = both a miss and a hallucination

        # Fields present in pred but not in gold -> pure FP.
        for field_name in pred_fields:
            if field_name not in gold_fields:
                fp += 1

    return _prf1_from_counts(tp, fp, fn, support)


def score_entities(
    pred_entities: Iterable[list[dict[str, Any]]],
    gold_entities: Iterable[list[dict[str, Any]]],
) -> PRF1:
    """Score NER using set-level F1 over (type, normalized_text) tuples.

    Offsets (``start``/``end``) are ignored because IE SFT outputs rarely
    include trustworthy offsets. If the same (type, text) pair occurs
    multiple times in gold, each occurrence is counted once against a
    multiset of predictions (so duplicated predictions don't inflate TP).

    Args:
        pred_entities: per-record list of entity dicts from predictions.
        gold_entities: per-record list of entity dicts from gold.

    Returns:
        PRF1 summary. ``support`` = total gold entities.
    """
    tp = fp = fn = support = 0
    for pred, gold in zip(pred_entities, gold_entities):
        gold_bag: dict[tuple[str, str], int] = {}
        for e in gold or []:
            key = (_normalize(e.get("type")), _normalize(e.get("text")))
            gold_bag[key] = gold_bag.get(key, 0) + 1
        support += sum(gold_bag.values())

        remaining = dict(gold_bag)  # copy; decremented as we match
        for e in pred or []:
            key = (_normalize(e.get("type")), _normalize(e.get("text")))
            if remaining.get(key, 0) > 0:
                remaining[key] -= 1
                tp += 1
            else:
                fp += 1
        fn += sum(remaining.values())

    return _prf1_from_counts(tp, fp, fn, support)


def score_relations(
    pred_rels: Iterable[list[dict[str, Any]]],
    gold_rels: Iterable[list[dict[str, Any]]],
    require_types: bool = False,
) -> PRF1:
    """Score RE using set-level F1 over relation triples.

    By default the tuple key is ``(head, relation, tail)`` (lenient).
    When ``require_types=True`` the key becomes
    ``(head, head_type, relation, tail, tail_type)`` (stricter, closer
    to the "strict" variant used in DocRED/CoNLL04).
    """
    tp = fp = fn = support = 0

    def _key(r: dict[str, Any]) -> tuple:
        if require_types:
            return (
                _normalize(r.get("head")),
                _normalize(r.get("head_type")),
                _normalize(r.get("relation")),
                _normalize(r.get("tail")),
                _normalize(r.get("tail_type")),
            )
        return (
            _normalize(r.get("head")),
            _normalize(r.get("relation")),
            _normalize(r.get("tail")),
        )

    for pred, gold in zip(pred_rels, gold_rels):
        gold_bag: dict[tuple, int] = {}
        for r in gold or []:
            k = _key(r)
            gold_bag[k] = gold_bag.get(k, 0) + 1
        support += sum(gold_bag.values())

        remaining = dict(gold_bag)
        for r in pred or []:
            k = _key(r)
            if remaining.get(k, 0) > 0:
                remaining[k] -= 1
                tp += 1
            else:
                fp += 1
        fn += sum(remaining.values())

    return _prf1_from_counts(tp, fp, fn, support)


# ---------------------------------------------------------------------------
# Top-level evaluator
# ---------------------------------------------------------------------------


def evaluate(
    predictions: list[str],
    gold_records: list[dict[str, Any]],
    task_types: list[str] | None = None,
) -> IEMetrics:
    """Compute IE metrics for a batch of predictions against gold records.

    Args:
        predictions: raw model output strings, one per gold record (same order).
        gold_records: canonical records as dicts (``to_canonical_dict()`` output).
        task_types: which tasks to score. Defaults to the union of
            task_types actually present across gold. Values: ``"kv"``,
            ``"entity"``, ``"relation"``.

    Returns:
        An ``IEMetrics`` summary. Only the requested tasks are populated.
    """
    if len(predictions) != len(gold_records):
        raise ValueError(
            f"Length mismatch: {len(predictions)} predictions vs "
            f"{len(gold_records)} gold records."
        )

    n = len(gold_records)
    parsed: list[dict[str, Any]] = []
    parse_failures = 0
    for raw in predictions:
        p, ok = _parse_prediction_with_status(raw or "")
        if raw.strip() and not ok:
            parse_failures += 1
        parsed.append(p)

    # Figure out which tasks to score.
    if task_types is None:
        active: set[str] = set()
        for g in gold_records:
            active.update(g.get("task_types") or [])
        task_types = sorted(active) or ["kv", "entity", "relation"]

    metrics = IEMetrics(n_records=n, n_parse_failures=parse_failures)

    if "kv" in task_types:
        pred_kvs = [p["kv"] for p in parsed]
        gold_kvs = [(g.get("answer") or {}).get("kv", {}) or {} for g in gold_records]
        metrics.kv = score_kv(pred_kvs, gold_kvs)

    if "entity" in task_types:
        pred_ents = [p["entity"] for p in parsed]
        gold_ents = [
            (g.get("answer") or {}).get("entity", []) or [] for g in gold_records
        ]
        metrics.entity = score_entities(pred_ents, gold_ents)

    if "relation" in task_types:
        pred_rels = [p["relation"] for p in parsed]
        gold_rels = [
            (g.get("answer") or {}).get("relation", []) or [] for g in gold_records
        ]
        metrics.relation = score_relations(pred_rels, gold_rels, require_types=False)
        metrics.relation_typed = score_relations(
            pred_rels, gold_rels, require_types=True
        )

    logger.info(
        "Eval summary: n=%d parse_failures=%d "
        "kv_f1=%.4f entity_f1=%.4f relation_f1=%.4f",
        n,
        parse_failures,
        metrics.kv.f1 if metrics.kv else -1,
        metrics.entity.f1 if metrics.entity else -1,
        metrics.relation.f1 if metrics.relation else -1,
    )
    return metrics


if __name__ == "__main__":
    # Quick smoke test.
    golds = [
        {
            "id": "1",
            "task_types": ["kv"],
            "answer": {"kv": {"name": "Alice", "age": "30"}},
        },
        {
            "id": "2",
            "task_types": ["entity"],
            "answer": {"entity": [{"type": "PER", "text": "Bob"}]},
        },
    ]
    preds = [
        '{"kv": {"name": "Alice", "age": "29"}}',
        '{"entity": [{"type": "PER", "text": "Bob"}]}',
    ]
    print(json.dumps(evaluate(preds, golds).to_dict(), indent=2))
